# Generated by Django 5.0.4 on 2024-04-29 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_categories_options_alter_categories_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contact.categories'),
        ),
    ]
