# Generated by Django 5.0.4 on 2024-05-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_contact_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.IntegerField(max_length=13, verbose_name='Telefone'),
        ),
    ]
