# Generated by Django 5.0.4 on 2024-05-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos', verbose_name='Foto'),
        ),
    ]
