# Generated by Django 5.0.4 on 2024-05-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_contact_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.BigIntegerField(max_length=13, verbose_name='Telefone'),
        ),
    ]
